project:
  type: website

website:
  title: "izo_1026_logP"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - packages.qmd
      - data.qmd
      - methods.qmd
      - initial_model.qmd
      - model_1.qmd
      - model_2.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true


bibliography: references.bib

editor: visual

